apiVersion: apps/v1
kind: Deployment
metadata:
  name: runner
  namespace: github-runner
  labels:
    app: runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: runner
  template:
    metadata:
      labels:
        app: runner
    spec:
      containers:
      - name: runner
        image: pwnedio/github-runner:latest
        imagePullPolicy: Always
        env:
        - name: GITHUB_OWNER
          value: tech-adai
        - name: GITHUB_REPOSITORY
          value: portal-backend
        - name: GITHUB_PERSONAL_TOKEN 
          valueFrom:
            secretKeyRef:
              name: github-secret-fitwel
              key: GITHUB_PERSONAL_TOKEN